# Generated by Django 4.2.4 on 2023-09-06 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_app', '0003_alter_user_workout_user_id_alter_workout_exercises'),
        ('workout_program_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_workout_program',
            name='user',
        ),
        migrations.AddField(
            model_name='user_workout_program',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userWorkoutPrograms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout_program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout_program',
            name='workouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='workout_programs', to='workout_app.workout'),
        ),
    ]
