# Generated by Django 4.2.4 on 2023-09-01 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_program_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField()),
                ('workout_details', models.TextField()),
                ('parent_program', models.ManyToManyField(blank=True, related_name='workouts', to='workout_program_app.workout_program')),
            ],
        ),
        migrations.CreateModel(
            name='User_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField()),
                ('workout_details', models.TextField(blank=True)),
                ('parent_program', models.ManyToManyField(blank=True, related_name='workouts', to='workout_program_app.user_workout_program')),
                ('user', models.ManyToManyField(blank=True, related_name='user_workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
