# Generated by Django 4.2.4 on 2023-09-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_workout',
            old_name='user',
            new_name='user_id',
        ),
    ]
