# Generated by Django 4.2.4 on 2023-09-04 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_program_app', '0002_user_workout_program_workout_program_and_more'),
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='app_user',
        ),
        migrations.AddField(
            model_name='workout',
            name='parent_program',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='workout_program_app.workout_program'),
        ),
        migrations.CreateModel(
            name='User_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(unique=True)),
                ('workout_details', models.TextField()),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workouts', to=settings.AUTH_USER_MODEL)),
                ('parent_program', models.ManyToManyField(blank=True, related_name='workouts', to='workout_program_app.user_workout_program')),
            ],
        ),
    ]
