# Generated by Django 4.2.4 on 2023-09-06 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_app', '0005_rename_user_id_exercise_created_by'),
        ('workout_app', '0002_rename_user_user_workout_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workout',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWorkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='workouts', to='exercise_app.exercise'),
        ),
    ]
