# Generated by Django 4.2.4 on 2023-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_alter_exercise_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(max_length=30),
        ),
    ]
