# Generated by Django 4.2.4 on 2023-09-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_app', '0003_rename_user_user_exercise_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='created_by',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user_exercise',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userExercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
