# Generated by Django 4.2.4 on 2023-09-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_rename_created_by_exercise_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
